### ISSUE TITLE
create peerauthentications for epp and em

### ISSUE THREAD

**Issue by grischperl** [kyma-project/eventing-manager#200]
## Description

both pods (epp and em) must be scrapable.

this requires a peerauthentication similar to:

```
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  labels:
    app.kubernetes.io/name: eventing-publisher-proxy
    app.kubernetes.io/version: 0.1.0
  name: eventing-publisher-proxy-metrics
  namespace: kyma-system
spec:
  portLevelMtls:
    "9090":
      mode: PERMISSIVE
  selector:
    matchLabels:
      app.kubernetes.io/name: eventing-publisher-proxy
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  labels:
    app.kubernetes.io/instance: eventing
    app.kubernetes.io/name: controller
  name: eventing-manager-metrics
  namespace: kyma-system
spec:
  portLevelMtls:
    "8080":
      mode: PERMISSIVE
  selector:
    matchLabels:
      app.kubernetes.io/instance: eventing-manager
      app.kubernetes.io/name: eventing-manager
```

> hint: 1. check if CRD is available on cluster. 2. if so, create peer authentication

## Acceptance:
- [ ] The new resources shall be removed once the module is gone
   > Hint: Owner Reference
