### ISSUE TITLE
Invalid Eventing CR status conditions

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/eventing-manager#506]
**Description**

The Eventing CR status conditions is not correct after configuring the EventMesh secret correctly.

**Steps to reproduce**

- Provision a Kyma cluster.
- Enable the Eventing module **1.1.0** with empty backend.
- Check the Eventing CR status conditions:
  ```yaml
  status:
    activeBackend: ""
    conditions:
    - lastTransitionTime: "2024-02-23T10:50:51Z"
      message: Backend config is not provided. Please specify a backend.
      reason: BackendNotSpecified
      status: "False"
      type: BackendAvailable
    specHash: 0
    state: Warning
  ```
- Create a proper EventMesh secret.
- Configure the EventMesh secret properly in the Eventing CR.
- Wait until the Eventing CR is ready.
- Check the Eventing CR status conditions:
  ```yaml
  status:
    activeBackend: EventMesh
    conditions:
    - lastTransitionTime: "2024-02-23T10:50:51Z"
      message: Backend config is not provided. Please specify a backend.
      reason: BackendNotSpecified
      status: "False"
      type: BackendAvailable
    - lastTransitionTime: "2024-02-23T11:03:16Z"
      message: Webhook is available
      reason: Ready
      status: "True"
      type: WebhookReady
    - lastTransitionTime: "2024-02-23T11:03:16Z"
      message: Subscription manager is ready
      reason: EventMeshSubscriptionManagerReady
      status: "True"
      type: SubscriptionManagerReady
    - lastTransitionTime: "2024-02-23T11:03:38Z"
      message: Publisher proxy is deployed
      reason: Deployed
      status: "True"
      type: PublisherProxyReady
    publisherService: eventing-publisher-proxy.kyma-system
    specHash: -3902697728114176809
    state: Ready
  ```
- The value of the condition **BackendAvailable** is still **False** which is not correct.
